version: '3.9'

networks:
  monitoring:
    name: monitoring
  inference:
    name: inference

services:
  inference_stable:
    build: 
      context: .
      args:
        PORT: 5000
    image: inference:stable
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - monitoring 
      - inference 
    
  inference_canary:
    build: 
      context: .
      args:
        PORT: 5001
    image: inference:canary
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - monitoring
      - inference

  nginx:
    image: nginx:mainline-alpine3.18-slim
    container_name: load_balancer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8082:8082
    depends_on:
      - inference_stable
      - inference_canary
    networks:
      - inference

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - inference
    environment:
      MYSQL_ROOT_PASSWORD: temp
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql:
