global:
  scrape_interval: 10s

# rule_files:
#   - 'rules.yml'

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 30s
    static_configs:
      - targets: ['cadvisor:8080']
  
  - job_name: 'inference_canary'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['inference_canary:5001'] 

  # - job_name: 'node-exporter'
  #   scrape_interval: 15s
  #   static_configs:
  #     - targets: ['node-exporter:9100']


